import os

CHART_SERVICE_URL: str = os.getenv("CHART_SERVICE_URL", "")
CHART_SERVICE_RESPONSE_TIMEOUT: int = int(
    os.getenv("CHART_SERVICE_RESPONSE_TIMEOUT", 10),
)

TELEGRAM_BOT_TOKEN: str = os.getenv("TELEGRAM_BOT_TOKEN", "")
SPREADSHEET_ID: str = os.getenv("SPREADSHEET_ID", "")
WEBHOOK_HOST: str = os.getenv("DETA_SPACE_APP_HOSTNAME", "")
SERVICE_ACCOUNT_FILE_PATH: str = os.getenv("SERVICE_ACCOUNT_FILE_PATH", "")

WELCOME_MD_FILE_PATH: str = os.getenv("WELCOME_MD_FILE_PATH", "")
HELP_MD_FILE_PATH: str = os.getenv("HELP_MD_FILE_PATH", "")

OVERVIEW_SHEET_NAME: str = os.getenv("OVERVIEW_SHEET_NAME", "Overview")
